# Generated by Django 5.0.2 on 2024-02-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links_app', '0002_rename_choice_text_word_word_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='word_1',
            field=models.CharField(default='SOME STRING', max_length=20),
        ),
        migrations.AddField(
            model_name='category',
            name='word_2',
            field=models.CharField(default='SOME STRING', max_length=20),
        ),
        migrations.AddField(
            model_name='category',
            name='word_3',
            field=models.CharField(default='SOME STRING', max_length=20),
        ),
        migrations.DeleteModel(
            name='Word',
        ),
    ]
