# Generated by Django 5.0.2 on 2024-02-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links_app', '0003_category_word_1_category_word_2_category_word_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='word_1',
            field=models.CharField(default='UNDEFINED', max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='word_2',
            field=models.CharField(default='UNDEFINED', max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='word_3',
            field=models.CharField(default='UNDEFINED', max_length=20),
        ),
    ]
